// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYeUaeuGYPYTcj3k9qIrmJckA-TxLEaj4',
    appId: '1:726234356209:web:3eb924b7785e58b1528c50',
    messagingSenderId: '726234356209',
    projectId: 'attendance-app-final-9303e',
    authDomain: 'attendance-app-final-9303e.firebaseapp.com',
    storageBucket: 'attendance-app-final-9303e.appspot.com',
    measurementId: 'G-4BFES1FNB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJrCTacmFT3Q9tNZHoVBKSFKtuqH310CQ',
    appId: '1:726234356209:android:6edc3c4f9779ba09528c50',
    messagingSenderId: '726234356209',
    projectId: 'attendance-app-final-9303e',
    storageBucket: 'attendance-app-final-9303e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBErigyUYqQUZU3VY6x-G2BjMJB4UYi5vU',
    appId: '1:726234356209:ios:7f3c511231097ea0528c50',
    messagingSenderId: '726234356209',
    projectId: 'attendance-app-final-9303e',
    storageBucket: 'attendance-app-final-9303e.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBErigyUYqQUZU3VY6x-G2BjMJB4UYi5vU',
    appId: '1:726234356209:ios:7f3c511231097ea0528c50',
    messagingSenderId: '726234356209',
    projectId: 'attendance-app-final-9303e',
    storageBucket: 'attendance-app-final-9303e.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYeUaeuGYPYTcj3k9qIrmJckA-TxLEaj4',
    appId: '1:726234356209:web:a589b270df5c6162528c50',
    messagingSenderId: '726234356209',
    projectId: 'attendance-app-final-9303e',
    authDomain: 'attendance-app-final-9303e.firebaseapp.com',
    storageBucket: 'attendance-app-final-9303e.appspot.com',
    measurementId: 'G-NQMNW9VL9D',
  );

}